### PR TITLE
Setting 'feed_url' to the current feed

### PR DESCRIPTION
**Pull request by oddevan**
Copy-pasted some code from the WP documentation since the code used by the Atom feed generator echos instead of returning. I'm happy to hack on this a little more if you feel a more elegant solution is needed.

### CODE REVIEW

**Comment by danielpunkass** [comment]
I assume code in WordPress docs is GPL. We should take care not to paste in GPL code because it is not compatible with the plugin's license. (Or we should reconsider the license. GPL might make sense for a WP plugin as much as I dislike it in general.)

**Comment by manton** [comment]
Hmm, good point @danielpunkass. Fighting the GPL in this case may not be worth it. I'm open to changing the license if people agree.

**Comment by oddevan** [comment]
@danielpunkass I honestly hadn't considered license implications, so that's definitely on me.

Would using an output buffer to capture the `self_link()` function output work (assuming [this blog post](http://www.tequilafish.com/2009/02/10/php-how-to-capture-output-of-echo-into-a-local-variable/) is accurate...)?

**Comment by oddevan** [comment]
OK, I've updated the code to call the `self_link()` function and capture the output. Hopefully this removes any potential GPL entanglements; either way, I like it better.

**Comment by manton** [comment]
Thanks, this seems like a good compromise for now. I'm leaning toward changing the license, but in the meantime it's good to have the feed URL correct.

**Pull request merged**
